kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: app
spec:
  scaleTargetRef:
    # point the HPA at the sample application
    # you created above
    apiVersion: apps/v1
    kind: Deployment
    name: app
  # autoscale between 1 and 10 replicas
  minReplicas: 2
  maxReplicas: 6
  metrics:
  # use a "Pods" metric, which takes the average of the
  # given metric across all pods controlled by the autoscaling target
  - type: Pods
    pods:
      # use the metric that you used above: pods/http_requests
      metricName: slpocapp_request_operations_per_second
      # target 500 milli-requests per second,
      # which is 1 request every two seconds
      targetAverageValue: 2000m
