apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    app: app
spec:
  containers:
  - name: app
    image: myoungmediero/app:latest
    command: ['python', 'main.py']
    ports:
    - containerPort: 8000